### ISSUE TITLE
Beam size

### ISSUE THREAD

**Issue by atemkeng** [atemkeng/Windowing-Functions#1]
How I can measure the beam width ( "at the Full width at half maximum or at the first null" ) of a specific telescope? I need to know how the beam varies as a function of the telescope integration time. Please could some one  advise me the approach I can use for this? Thanks

**Comment by o-smirnov** [comment]
If you mean the primary beam of the antenna, then integration time doesn't enter into it at all. FWHM ~ 1.2*lamda/D is a good guideline though.

**Comment by atemkeng** [comment]
I am sorry, I meant the Primary  Beam, I want to measure this from the MS and find an optimal filter ("with sharp pass-band") that recover signals within the Primary Beam main lobe ("within the main lobe first null?"). For LoFAR this method will not work, as its Field of View is much larger than the primary beam.

**Comment by o-smirnov** [comment]
Generally, you can't determine the primary beam from the MS, you just have to know it in advance. (In principle, there's a DISH_DIAMETER field in the ANTENNA subtable, but this is often not filled correctly, so don't rely on it). I suggest you leave it as an external option to your scripts, so that one may specify:
- directly a FOV in degrees,
- or a dish size in meters, in which case FOV = 2_FWHM = 2_1.2*lambda/dish_size

I'm not sure what you mean by the LOFAR comment. FOV and primary beam are almost the same thing (i.e. FOV is usually taken to be the main lobe of the PB, or the main lobe plus first sidelobe), except in VLBI, where FOV << PB because it is limited by smearing instead. LOFAR has a very large PB and thus a very large FOV. Filters should work even better in this regime, as the FOV will have a conversely "small" footprint in uv space.

**Comment by atemkeng** [comment]
The length of a window determines the transition band of its FT. Thus, for an optimal filter (we need sharp transition band), the Hires MS needs to have sufficient resolution in time ("tiny integration, dt") and frequency ("very narrow channel width, df") in such a way that, if DT and DF are the MS critical sampling rate ("the Low Res integration time") and the bandwidth of the low res MS respectively then  we have DT = n1_dt ; DF = n2_df , n1 and n2 will determine the image plane transition band. So if we want an optimal filter, we must keep dt and df small to have large n1 and n2 while DT and DF remain constant. This is actualy the same concept with the overlap.
But as a draw back, there must be sufficient computing resources to handle the data before compression.

I evaluated this but in decibel, if N is the width of the window let us say in time, then the transition band of the Fourier Transform of the window follows: TB = Const/ N;
Where the constant is approximately equivalent to 4 and TB is the width in decibel of the transition band, measured from where the curve just barely leaves one, to where it almost reaches zero.
If we can express TB in degree, then from the number of time and frequency bins to be average, we will know the sharpness of the Transition band in the sky. Thus, to  express the transition band as a function  of n1 and n2. More narrower the transition band, then more suppression of near by sources  to the FoV.

**Comment by atemkeng** [comment]
For example, a sinc(FoV_pi_u), the transition band sharpness is within [FoV/2,  FoV/2+Tb] here; 
Tb ~4/(n_t + n_otime + n_freq + n_ofreq) . with Tb in radian and n_t , n_otime, n_freq, n_ofreq are the number of average time bins, frequency bins, overlap time bins, overlap time frequency bins respectively. Sharp Transition band will require (n_t + n_otime + n_freq + n_ofreq) ~675 times and/or frequency bins. This is standard for all arrays because the FoV doesn't affect the transition band with windowing function. Tb explain why (" if you remember, we were about to know why at a certain overlap rate, the window doesn't contribute any more in signal suppression and recovery"), this because (n_t + n_otime + n_freq + n_ofreq) will never tend to infinity in real life and at a certain limit the Fourier Transform of sinc(FoV_pi_u) tends to 1 truncated boxcar (Not the ideal as we know) . Here there is another thing to know, what is the overlap threshold? Belong this  threshold, we are giving the CPU more unuseless job.
