### ISSUE TITLE
Source suppression as a function of radius out to 30deg

### ISSUE THREAD

**Issue by atemkeng** [atemkeng/Windowing-Functions#2]
You will find in the directory /net/elwood/home/atemkeng/NVSS/Temple  two pdfs, one "plot.pdf" a source suppression as a function of radius of the  filters mentioned on the plot. The other "compression-noise.pdf" is a table comparing the noise, the noise ratio and the compression rate. Notice that the integration of the low resolution is the critical time sampling rate of the interferometer longest baseline (see the option "usecriticalsamplingrate =True"). You will find in the file wfconfigfileVLAC.cfg all the setup I used to run the simulation. Notice that you can run this setup  also by 

> > python  runwf-fluxradius.py wfconfigfileVLAC.cfg
> > This will produce:
> > 1:) a *.png for each window you select
> > 2:) *flux-radius.data :a pickle file containing the output results of all the windows you selected.
> > 3:) *.tex a latex code containing the table for noise, noise ration and compression rate of all windows you select
> > 4:) *.pdf the table in pdf
> > 5:) *compression-noise.data a pickle file containing the information for noise and compression for the windows.
> > you can make a wfconfigfileMeerKat.cfg from wfconfigfileVLAC.cfg and run both of them; 
> > python  runwf-fluxradius.py wfconfigfileVLAC.cfg wfconfigfileMeerKat.cfg

These options are not yet activated in the configuration file "wfconfigfileVLAC.cfg"
[bessel_hamming]
[bessel_blackman]
[bessel_hanning]
[butterwordth]
 also few of subsections.
I have to write a read me when this will finish. The is a configuration file for long synthesis with the same philosophy; I will give you during the week.

**Comment by o-smirnov** [comment]
In plot.pdf, could you make the y axis logarithmic please? Kind of hard to make out the results otherwise.

**Comment by atemkeng** [comment]
You have two plots in the directory; plot_Zom_close-0.5deg.pdf the Zom around 0.5 degree and the actual plot.pdf in log scale.

**Comment by atemkeng** [comment]
Please have a look on these files. I ran a set of BDWF's with the windows on these plots, it is taking some time with the flagging.
plot-log-scale-vs-radius.pdf; plot_Zom_close-0.5deg.pdf; vlac-compression-noise.pdf
