### ISSUE TITLE
PSF distortion for out Primary Beam "main lobe" sources

### ISSUE THREAD

**Issue by atemkeng** [atemkeng/Windowing-Functions#3]

**Comment by atemkeng** [comment]
I^{D}_{l,m} = (F^{H}.A.I^{sky})_{l,m} describes the PSF for each location in the sky with windowing functions. The equation is from the paper draft (Eq.12). I presented this distortion on the last report doing simulation by moving a single source in the sky and computed the PSF using multiple MS each encapsulating a source and I made an image from that. For instance, I have to find  a fast algorithm to compute the previous equation, without using imager this implies some sort of Fourier interpolation from uv space to l,m space. So we can then use this during deconvolution implying multiple PSF for a single sky map. We can start by partitioning the map across 1degX1deg for example and assign a specific PSF to each area  to reduce the cost. Please advise if this makes sense?

**Comment by atemkeng** [comment]
I have calculated the pseudo psf estimation at the field centre and at various location on a sky grid from a direct calculation and compared to the one produced with imager. They look similar and confirmed the simulated result. Now I am very close to derive the function f(l,m,window,compression factor) that by multiplying it with the nominal PSF{l0,m0}, we easily derive this pseudo PSF{l,m}=f(l,m,sinc,compression factor)PSF{l0,m0} .

**Comment by o-smirnov** [comment]
That's excellent progress!

**Comment by atemkeng** [comment]
look at https://github.com/atemkeng/Windowing-Functions/blob/master/reports/report-2014-10-20
look this link also http://legacy.nrao.edu/alma/memos/html-memos/alma389/memo389.pdf

**Comment by atemkeng** [comment]
look at this repertory on elwood, /home/atemkeng/Temple_PSF/Clean_map_source_with_diff_psf, you will find two sub-repertories clean00deg  clean15deg  and a dirty image "imagerdirty.fits" containing a simulated source at 1.5deg. Each of the sub-folders contain a restored, residual images of "imagerdirty.fits" after clean with two different PSFs. One the nominal PSF and the other a pseudo psf at 1.5deg.

**Comment by cyriltasse** [comment]
Hey Marcelin, what do you call the Pseudo-PSF. Is it the one calculated from direct calculation, or the calculated with the fast method?

**Comment by atemkeng** [comment]
The one from direct calculation, I wanted  to see how a restored image will look like.

**Comment by o-smirnov** [comment]
(@atemkeng , please upload your plot from today in PNG format.)

So, designating the PSF at location l,m as P_{l,m}(x,y), and the PSF at 0 as P_0(x,y) -- the function f that Marcellin plots is f(x,y;l,m) = P_{l,m}(x,y)/P_0(x,y).

Now, there's a few approaches: 
1. Pre-compute by brute force P_{l,m}(x,y) for a number of l,m positions (i.e. {-30,0,30},{-30,0,30})
2. For the in-between points, approximate P_{l,m}(x,y) by interpolating at each x,y between the pre-tabulated PSFs from step 1.

![plot](https://cloud.githubusercontent.com/assets/6806881/4844980/cfa94a92-6040-11e4-8c64-e11a574a1fbd.png)

**Comment by atemkeng** [comment]
Fast Method: The problem is when I am using fft, the shift function does not work well, so I try to figure out how to manage these. Look at the plot below. 
![plot](https://cloud.githubusercontent.com/assets/6806881/4942799/0cb4ebb8-65ef-11e4-9a09-249e95b4c5a8.png)

**Comment by atemkeng** [comment]
PSF Maths derivation Updated on 
https://github.com/atemkeng/Windowing-Functions/tree/master/PaperPSF
